accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns=[
    path(r'^register/$', views.register, name='register'),
    path(r'^logout/$',views.user_logout,name='logout'),
    path(r'^profile/(?P<pk>\d+)/$', views.ProfileDetailView.as_view(), name='profile'),

]

heartdisease/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from accounts import views
from heartdisease import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.user_login,name='user_login'),
    path('^accounts/',include('accounts.urls')),
    path('^predict/',include('prediction.urls')),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prediction/urls.py
from django.urls import path
from . import views
app_name='predict'
urlpatterns=[
path(r'^(?P<pk>\d+)$',views.PredictRisk,name='predict')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

from django.shortcuts import resolve_url


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_pic = models.ImageField(upload_to='profile_pics', default="1.jpg")

    def __str__(self):
        return self.user.username
# Create your models here.

accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter username'}
    ), required=True, max_length=50)

    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Email Id'}
    ), required=True, max_length=50)

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter password'}
    ), required=True, max_length=50)

    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm password'}
    ), required=True, max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "Password and Confirm password does not match"
            )


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        widgets = {'username': forms.TextInput(attrs={'readonly': 'True'})}

accounts/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm, UpdateProfileForm
from django.views.generic import DetailView,UpdateView,TemplateView
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import UserProfileInfo, User
from django.shortcuts import get_object_or_404
# Create your views here.



@login_required
def user_logout(request):
    # del request.session['user_id']
    request.session.flush()
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))




def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

        if registered:
            return HttpResponseRedirect(reverse('user_login'))

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'accounts/register.html',{'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):


    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')



        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                request.session['user_id'] = user.profile.pk

                return HttpResponseRedirect(reverse('predict:predict', kwargs={'pk': user.profile.pk}))


            else:
                return HttpResponse("Account not active")
        else:
            print("Tried login and failed")
            print("username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")

    else:
        return render(request, 'accounts/login.html', {})

class ProfileDetailView(LoginRequiredMixin, DetailView):
    login_url = '/'
    redirect_field_name = '/'
    model = UserProfileInfo
    template_name = 'accounts/profileview.html'

    def get_context_data(self, **kwargs):
        if self.request.session.has_key('user_id'):
            u_id = self.request.session['user_id']
            context = super(ProfileDetailView, self).get_context_data(**kwargs)
            context['user_id'] = u_id


        return context

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'><!--web font-->
    <title>Heart disease prediction</title>
</head>
<body style="background-image: url('{% static 'images/1.jpg' %}')">
	<!-- main -->
	<div class="agileits-main">
	<div class="w3top-nav">

				<div class="w3top-nav-left">
					<h1 style="color:white;">          Heart Disease Prediction System</h1>
				</div>

				<div class="w3top-nav-right">
					<ul>

						<li><a href="{% url 'accounts:register' %}">Signup</a></li>
						<li><a href="/admin">Admin login</a></li>
					</ul>
				</div>

		</div>

    <div class="header-main">
    <h2>Login Now</h2>
			<div class="header-bottom">
				<div class="header-right w3agile">
					<div class="header-left-bottom agileinfo">
            <form role="form" action=" {% url 'user_login' %}" method="post">
            {% csrf_token %}
							<div class="icon1">
								<input  type="text" name="username" placeholder="Username" >
							</div>
							<div class="icon1">
								<input type="password"  name="password" placeholder="Password"/>
							</div>

							<div class="bottom">
								<input type="submit" value="Log in">
							</div>
					</form>&nbsp;

					</div>
				</div>
			</div>
	</div>

	</div>
	<!-- //main -->
</body>

</html>

accounts/templates/accounts/profileview.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />


    <meta charset="UTF-8">
    <title></title>
    <style>
        body {background-color: hsla(89, 43%, 51%, 0.3);}
    </style>
</head>

<body style="background-image: url('{% static 'images/3.jpg' %}');;
  background-repeat: no-repeat;
  background-attachment: fixed;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-repeat: no-repeat; background-size: cover; background-position: top center;" >

    <div class="wrapper">
        <div class="page-header page-header-small"  style="max-height: 0px; ">
            </div>
<!--            nav-->
             <nav class="navbar navbar-expand navbar-transparent" >
        <div class="container">
            <div class="collapse navbar-collapse justify-content-end" id="navigation" >
                <ul class="navbar-nav nav-tabs">

<!--                      <li class="nav-item"><a href="{% url 'accounts:profile' pk=user_id %}" class="btn btn-neutral">Profile</a></li>-->
                       <li class="nav-item"> <a href="{% url 'predict:predict' pk=user_id %}" class="nav-link text-secondary">

                         <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi d-block mx-auto mb-1" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053.918 3.995.78 5.323 1.508 7H.43c-2.128-5.697 4.165-8.83 7.394-5.857.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17c3.23-2.974 9.522.159 7.394 5.856h-1.078c.728-1.677.59-3.005.108-3.947C13.486.878 10.4.28 8.717 2.01L8 2.748ZM2.212 10h1.315C4.593 11.183 6.05 12.458 8 13.795c1.949-1.337 3.407-2.612 4.473-3.795h1.315c-1.265 1.566-3.14 3.25-5.788 5-2.648-1.75-4.523-3.434-5.788-5Zm8.252-6.686a.5.5 0 0 0-.945.049L7.921 8.956 6.464 5.314a.5.5 0 0 0-.88-.091L3.732 8H.5a.5.5 0 0 0 0 1H4a.5.5 0 0 0 .416-.223l1.473-2.209 1.647 4.118a.5.5 0 0 0 .945-.049l1.598-5.593 1.457 3.642A.5.5 0 0 0 12 9h3.5a.5.5 0 0 0 0-1h-3.162l-1.874-4.686Z"/>
                        </svg>
                        Predict
                       </a></li>

<!--                      <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="btn btn-neutral">Logout</a></li>-->
                    <li class="nav-item"> <a href="{% url 'accounts:logout' %}" class="nav-link text-secondary">

                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi d-block mx-auto mb-1" width="24" height="24" viewBox="0 0 16 16">
                          <path d="M7.5 1v7h1V1h-1z"/>
                          <path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z"/>
                        </svg>
                        Log Out
                       </a></li>

                </ul>
            </div>
        </div>
    </nav>

<!--            nav-->
            <div class="container">
                <div class="content-center">
                    <div class="photo-container" style="width:300px; ">
                        <img src="{{userprofileinfo.profile_pic.url}}" />
                    </div>
                    <h2 class="title text-white" >{{ userprofileinfo.user.username }}</h2>
                    <p class="h5 text-white">{{ userprofileinfo.user.email }}</p>


                    </div>
                </div>
            </div>


    <div class="container" >
    <div class="card-header bg-primary btn-round text-white " style="padding:20px; border:30px; margin :50px; text-align: center;">Predictions</div>
        <hr>


        {% for pred in userprofileinfo.predict.all  %}
            <br>

             <div class="card card-login" style="width: 100%">
                    <div class="card-header bg-dark text-white" style="height: 60px;"> Prediction : {{ pred.num|safe}}   <br/> (0 for negative ; 1 for Positive)
                    </div>
                    <div class="container">
                        <br>
                        <p>Predicted by {{pred.profile}}</p>
                        <p>Age: {{pred.age}}</p>
                    </div>
                    <div class="card-footer bg-light" >Predicted on {{ pred.predicted_on }}</div>

            </div>
            <br>
        {% endfor %}


    </div>



</body>
<script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap_ui_kit.js' %}" type="text/javascript"></script>
</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/now-ui-kit.css' %}" rel="stylesheet" />



  </head>
  <body>

    <div class="section section-signup" style="background-image: url('{% static 'images/image 3.jpg' %}');-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-repeat: no-repeat; background-size: cover; background-position: top center; min-height: 700px;">

      <nav class="navbar navbar-expand  fixed-top navbar-transparent" >
              <div class="container">
                  <div class="collapse navbar-collapse justify-content-end" id="navigation" >
                      <ul class="navbar-nav nav-tabs">



                          {%if user.is_authenticated%}
                            <li class="nav-item"><a  href="{% url 'accounts:logout'%}" class="btn btn-neutral">Logout</a></li>
                            {%else%}
                            <li><a href="{% url 'user_login'  %}" class="btn btn-neutral">Login</a></li>
                            {%endif%}
                            <li class="nav-item"><a href="/admin" class="btn btn-neutral">Admin login</a></li>

                      </ul>
                  </div>
              </div>
          </nav>

    <div class="container" >
			<div class="row">
      <div class="card-signup card-plain" data-background-color="">


          {% if registered %}

          <h1>Thank you for registering!</h1>

          {% else %}

          <form role="form" enctype="multipart/form-data" method="post">
              {% csrf_token %}
              <div class="card-header text-center form-group">
							<h3 class="card-title title-up ">Sign Up</h3>

              {{ user_form}}
              {{ profile_form}}


            <button type="submit" class="btn btn-round bg-transparent border">Sign Up</button>
              </div>
          </form>
          {% endif %}
              </div>
    </div>
  </div>
</div>

</body>
</html>